feat: develop tables and relationships, describe schema for Prisma, and perform migration
Adobe-for-Alex/subscription-service pull request #12
Opened 2024-11-03 16:15 UTC by a9ek0

2024-11-03 19:44 UTC, a9ek0 commented on prisma/schema.prisma
> +  isActive      Boolean   @default(true)
Действует ли подписка на аккаунте

2024-11-03 19:44 UTC, a9ek0 commented on prisma/schema.prisma
> +  updatedAt     DateTime  @updatedAt
Когда был изменен пароль / Когда статус аккаунта менялся (isActive) / Прочие обновления записи

2024-11-03 19:44 UTC, a9ek0 commented on prisma/schema.prisma
> +  isActive      Boolean      @default(true)
Активна ли сессия

2024-11-03 19:47 UTC, a9ek0 commented on prisma/schema.prisma
> +}
Соглашусь

2024-11-03 20:24 UTC, Chamber6821 commented on prisma/schema.prisma
> +  isActive      Boolean   @default(true)
Тогда лучше назвать конкретно `subscription`

2024-11-03 20:25 UTC, Chamber6821 commented on prisma/schema.prisma
> +  isActive      Boolean      @default(true)
Зачем этот флаг, если есть `endedAt`?

2024-11-03 20:49 UTC, Chamber6821 commented on prisma/schema.prisma
> +}
Тогда удали эту таблицу

2024-11-03 20:49 UTC, Chamber6821 commented
@a9ek0 не делай миграцию на каждое изменение схемы, все равно придется переделывать ее. Так что лучше сгенерируй ее уже в конце PR

2024-11-03 20:52 UTC, Chamber6821 commented on prisma/schema.prisma
> +  updatedAt     DateTime  @updatedAt
И зачем нужен такой индикатор отвечающий за все подряд? Я думаю лучше заменить это на время последней проверки валидности аккаунта

2024-11-04 11:41 UTC, Chamber6821 requested changes

2024-11-04 11:41 UTC, Chamber6821 commented on prisma/schema.prisma
>  }
Зачем тебе отдельная таблица для аккаунтов, если тут связь 1 к 1 и тебе не нужно хранить информацию непосредственно об аккаунтах, тебе нужно лишь переодически проверять, что они живие

2024-11-04 12:17 UTC, Chamber6821 commented
Тебе нужно в сервисе управлять адоб аккаунтами через [adobe-api](https://github.com/Adobe-for-Alex/adobe-api), почтами на сервисе [mail.tm](https://docs.mail.tm/) и сессиями для [telegram-bot](https://github.com/Adobe-for-Alex/adobe-api). Изучи их апишки (вместо апишки ТГ бота смотри на свою апишку) и реши какие данные в БД необходимо хранить для управления всем этим, а какие данные будут __избыточны__. Не нужно делать кеш, лучше отправить лишние запросы к апишкам

2024-11-04 16:55 UTC, a9ek0 commented
@Chamber6821 что-то вроде этого?

```prisma
model Session {
  id            String    @id @default(uuid())
  email         String    // Почта аккаунта, для связи с Adobe API и Mail.tm
  inboxId       String?   // Идентификатор почтового ящика на Mail.tm
  startedAt     DateTime  @default(now())
  endedAt       DateTime?
  isActive      Boolean   @default(true)
}
```

2024-11-04 17:00 UTC, Chamber6821 commented
Да

2024-11-04 19:55 UTC, Chamber6821 requested changes

2024-11-04 19:55 UTC, Chamber6821 commented on prisma/schema.prisma
> +  adobeId      String?
Почему ты сделал их опциональными?

2024-11-04 20:05 UTC, a9ek0 commented on prisma/schema.prisma
> +  adobeId      String?
Вообще, я думал, что может создаваться тестовая сессия, которая не требует почты или связанного adobeid, но в целом сессия не может быть без уже существующих айдишнков. Поэтому все-таки лучше сделать их обязательными.

2024-11-04 21:32 UTC, Chamber6821 commented
Думаю нам этого для начала хватит, потом дополним по мере надобности. Сделай пожалуйста миграцию с нуля, т.е. удали ту старую и заного сделай

2024-11-04 21:44 UTC, Chamber6821 approved these changes

2024-11-04 21:44 UTC, merged