feat(mails): implement TmMails
Adobe-for-Alex/subscription-service pull request #26
Opened 2024-11-11 20:09 UTC by a9ek0

Fixes #19

2024-11-13 15:57 UTC, Chamber6821 requested changes

2024-11-13 15:58 UTC, Chamber6821 commented on src/mails/TmMails.test.ts
> +          token: 'test-token' // Ensure token is included
Ошибка. Сервис каждый раз отдает разные токены

2024-11-13 15:59 UTC, Chamber6821 commented on src/mails/TmMails.test.ts
> +      .reply(201, { token: 'test-token' }) // Mock the token endpoint
Если токен хранится в БД, разве должен объект обращаться за ним в сеть?

2024-11-13 17:35 UTC, a9ek0 commented
@Chamber6821 можешь пожалуйста посмотреть тест 'should send HTTP DELETE request to delete account' я уже не понимаю 
что там не так

2024-11-13 17:38 UTC, Chamber6821 requested changes

2024-11-13 17:38 UTC, Chamber6821 commented on src/mails/TmMails.test.ts
> +    expect(deleteRequests[0]?.headers.authorization).toBe('Bearer test-token')
Замени на `expect().toContainEqual({...})`

2024-11-13 17:38 UTC, Chamber6821 commented on src/mails/TmMails.ts
> +  constructor(private readonly id: string, private readonly token: string, private readonly api: any) {}
Лучше напиши конкретный тип для API

2024-11-13 17:38 UTC, Chamber6821 commented on src/mails/TmMails.test.ts
> +        return ''
Это вопрос. Зачем ты написал тут `return ''`? Он на что-то влияет? Если нет, то удали

2024-11-13 17:38 UTC, Chamber6821 commented on src/mails/TmMails.ts
>    }
Вынеси в отдельный файл в папку `mail`

2024-11-13 17:53 UTC, Chamber6821 requested changes

2024-11-13 17:53 UTC, Chamber6821 commented on src/mails/TmMails.ts
> +          createdAt: new Date(),
Не стоит указывать поля, которые заполняются автоматически

2024-11-13 17:53 UTC, Chamber6821 commented on src/mails/TmMails.ts
> +    }
Зачем этот `catch`?

2024-11-13 17:53 UTC, Chamber6821 commented on src/mails/TmMails.test.ts
> +    expect(deleteRequests[0]?.headers.authorization).toContainEqual('Bearer test-token')
Не. Вот так `expect(deleteReqeusts).toContaineEqual({path: ..., headers: ...})`

2024-11-13 17:53 UTC, Chamber6821 commented on src/mail/TmMail.ts
> +  constructor(private readonly id: string, private readonly token: string, private readonly api: AxiosInstance) {}
Напиши лучше каждое поле с новой строки для лучшей читабельности

2024-11-13 17:53 UTC, Chamber6821 commented on src/mails/TmMails.ts
> +import TmMail from '../mail/TmMail' // Add this import
Удаляй пожалуйста комментарии от GPT

2024-11-13 17:53 UTC, Chamber6821 commented on src/mails/TmMails.ts
>    }
Заинлайнь в месте использования. Приватных методов не должно быть в коде. К тому же он вызывается 1 раз

2024-11-14 08:47 UTC, Chamber6821 commented on src/mails/TmMails.test.ts
> +      .reply(201, { token: 'test-token' }) // Mock the token endpoint
@a9ek0

2024-11-14 08:47 UTC, Chamber6821 commented
@a9ek0 ответь тут пожалуйста https://github.com/Adobe-for-Alex/subscription-service/pull/26#discussion_r1840687586

2024-11-14 18:00 UTC, a9ek0 commented on src/mails/TmMails.test.ts
> +      .reply(201, { token: 'test-token' }) // Mock the token endpoint
@Chamber6821 я там коммит сразу сделал

2024-11-15 19:03 UTC, Chamber6821 commented on src/mails/TmMails.test.ts
> -    nock(mailTmApiBaseUrl) // to throw exception for all requests
@a9ek0 я попросил вернуть в исходное состояние. Для ускорения процесса я сделаю это сам, но обращай пожалуйста внимание на дельту на гитхабе и/или локально (`git diff`). Я часто ссылаюсь на состояния кода на разных коммитах и важно учитывать дельту (diff)

2024-11-15 20:21 UTC, Chamber6821 approved these changes

2024-11-15 20:26 UTC, Chamber6821 commented
Хьюстон, у нас проблемы

2024-11-15 20:26 UTC, Chamber6821 commented
Пойду смотреть, что я в правилах понаписал

2024-11-15 20:28 UTC, merged

2024-11-15 20:29 UTC, Chamber6821 commented
Я убал галочку "Требовать линейной истории"