Initial commit: Project setup
Adobe-for-Alex/subscription-service pull request #4
Opened 2024-10-24 18:48 UTC by a9ek0

Fixes #2

2024-10-24 19:19 UTC, Chamber6821 requested changes

2024-10-24 19:19 UTC, Chamber6821 commented on .github/workflows/deploy.yml
Удали этот workflow, он не подходит к проекту, я ошибся

2024-10-24 19:19 UTC, Chamber6821 commented on .github/workflows/lint.yml
Удали этот workflow, он не подходит к проекту, я ошибся

2024-10-24 19:19 UTC, Chamber6821 commented on .github/workflows/new-issue.yml
Удали этот workflow, он не подходит к проекту, я ошибся

2024-10-24 19:19 UTC, Chamber6821 commented on package.json
> +  "description": "Микросервис управляющий пользователями Adobe\r и предоставляющие сессионый доступ к подписке.\r В рамках сессии пользователю (не Adobe) по мере расходования подписки\r выдаются новы
Используй `\n` вместо `\r`

2024-10-24 19:32 UTC, Chamber6821 commented
Прошу прощения, я увидел, что не писал уточнений про язык. Подразумевался TypeScript

2024-10-25 12:59 UTC, Chamber6821 requested changes

2024-10-25 12:59 UTC, Chamber6821 commented on .github/workflows/yougile-tasks.yml
Зачем ты это удалил? Верни

2024-10-25 19:26 UTC, Chamber6821 commented
Ок. Посмотри как это сделано в telegram-bot/#6 и сделай на подобии. В целом шаблон для твоего проекта такой же как и у telegram-bot, только проще, так что можешь просто подождать пока я доделаю тот проект. Да, получилось как-то коряво. Надо было все таки мне изначально самому все заготовки сделать

2024-10-27 18:44 UTC, Chamber6821 commented
@a9ek0 я закончил делать Adobe-for-Alex/telegram-bot/#6, можешь от туда скопировать и все

2024-10-27 19:19 UTC, a9ek0 commented
@Chamber6821

2024-10-28 11:31 UTC, Chamber6821 requested changes
Ты потерял файл `.env.template`

Так же добавь инструкцию в README как это сделано в другом [репозитории](https://github.com/Adobe-for-Alex/adobe-api/commit/029934a564acd3b061b67e3702ec9b55085b9ea9#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R6-R28)

2024-10-28 11:31 UTC, Chamber6821 commented on docker-compose.yml
> +  bot:
Твой сервис явно не бот. [Пример](https://github.com/Adobe-for-Alex/adobe-api/blob/029934a564acd3b061b67e3702ec9b55085b9ea9/docker-compose.yml#L2)

2024-10-28 11:31 UTC, Chamber6821 commented on docker-compose.yml
> +      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
Твоему сервису не понадобится токен от телеграма

2024-10-28 11:31 UTC, Chamber6821 commented on package.json
> +  "license": "ISC",
Лучше удалить эти поля, вместо того, что бы оставлят пустыми

2024-10-28 11:31 UTC, Chamber6821 commented on package.json
> +    "telegraf": "^4.16.3"
Твой сервис не будет взаимодейсвовать с телеграмом

2024-10-28 11:31 UTC, Chamber6821 commented on src/index.ts
> +console.log(sayHello());
Лучше напиши сервер, который будет отвечать Hello World! [Пример](https://github.com/Adobe-for-Alex/adobe-api/blob/master/src/index.ts)

2024-10-28 11:31 UTC, Chamber6821 commented on package.json
> +    "dev": "pnpm dev:up && docker compose attach bot",
Когда изменишь имя в `docker-compose.yml`, эта строка должна измениться как в [примере](https://github.com/Adobe-for-Alex/adobe-api/blob/029934a564acd3b061b67e3702ec9b55085b9ea9/package.json#L13)

2024-10-28 15:00 UTC, Chamber6821 requested changes

2024-10-28 15:00 UTC, Chamber6821 commented on README.md
> +Сеовис подписок взаимодействует сnpm install express
Кажется мискликнул

2024-10-28 17:42 UTC, Chamber6821 approved these changes

2024-10-28 17:42 UTC, merged