feat: develop microservice interaction interfaces
Adobe-for-Alex/subscription-service pull request #8
Opened 2024-10-28 22:54 UTC by a9ek0

Fixes #7

2024-10-29 15:24 UTC, Chamber6821 commented
Покажи пример, как ты хочешь соединять эти абстракции

[Вот](https://github.com/yegor256/takes?tab=readme-ov-file#exception-handling) что, я имею в виду

2024-10-30 14:25 UTC, a9ek0 commented
async function example() {
  const service = await serviceFactory.create();
  const sessions = await service.sessions();
  
  const user = // ... get user from db
  const session = await sessions.open(user);
  
  const account = await session.account();
  const credentials = await user.credentials();
  
  if (await account.isSubscriptionValid()) {
    const webhook = await service.webhook();
    await webhook.notifyAccountUpdate(session, credentials);
  }
}

2024-10-30 14:25 UTC, a9ek0 commented
@Chamber6821

2024-10-30 16:33 UTC, Chamber6821 commented
https://github.com/Adobe-for-Alex/adobe-api/pull/5#issuecomment-2446095897

2024-10-30 16:35 UTC, Chamber6821 commented
https://github.com/Adobe-for-Alex/telegram-bot/pull/8#discussion_r1819606762

2024-10-30 16:44 UTC, Chamber6821 commented
Пример того, как может выглядеть сессия
```ts
interface Session {
  asJson(): Promise<Json>
}

interface Sessions {
  all(): Promise<Session[]>
  create(...): Promise<Session>
  withId(id: SessionId): Promise<Session | undefined>
  delete(id: SessionId): Promise<void>
}
```

2024-10-30 16:56 UTC, Chamber6821 commented
Пример обновления данных Adobe аккаунта для активной сессии. Все async/await я опускаю, что бы не загромождать код
```ts
// для каждой сессии раз в какое-то время

if (!session.valid()) {
  session.mail().delete()
  session.update(adobe.newAccount(mailServer.create()))
}
```

2024-10-30 17:01 UTC, Chamber6821 commented
Обновленный список интерфейсов, с учетом предыдущего сценария использования
```ts
interface Mail {
  address(): Promise<string>
  password(): Promise<string>
  delete(): Promise<void>
}

interface MailServer {
   create(): Promise<Mail>
}

interface Account {
  mail(): Promise<Mail>
}

interface Adobe {
  newAccount(mail: Mail): Promise<Account>
}

interface Session {
  mail(): Promise<Mail>
  update(mail: Mail): Promise<void>
}
```

2024-10-30 18:35 UTC, a9ek0 commented
### Example 1: Creating a new session

```ts
async function createNewSession(
  mailServer: MailServer,
  adobe: Adobe,
  sessions: Sessions
) {
  const mail = await mailServer.create();
  const account = await adobe.newAccount(mail);
  return sessions.create(await account.mail()).then(session => session.asJson());
}
```

### Example 2: Checking and updating session

```ts
async function validateAndUpdateSession(
  session: Session,
  mailServer: MailServer,
  adobe: Adobe
) {
  if (!await session.valid()) {
    const newMail = await mailServer.create();
    const newAccount = await adobe.newAccount(newMail);
    await session.update(await newAccount.mail());
  }
}
```

### Example 3: Getting session account details

```ts
async function getSessionAccount(
  sessions: Sessions,
  sessionId: string
) {
  const session = await sessions.withId(sessionId);
  if (!session) return null;

  const mail = await session.mail();
  return {
    email: await mail.address(),
    password: await mail.password()
  };
}
```

### Example 4: Closing a session

```ts
async function closeSession(
  sessions: Sessions,
  sessionId: string
) {
  const session = await sessions.withId(sessionId);
  if (!session) return;

  await session.mail().then(mail => mail.delete());
  await sessions.delete(sessionId);
}
```

### Example 5: Session webhook notification

```ts
async function handleSessionUpdate(
  sessionId: string,
  mail: Mail
) {
  const webhookUrl = process.env.SESSION_UPDATED_WEBHOOK_URL;
  if (!webhookUrl) throw new Error('Webhook URL not configured');

  await fetch(webhookUrl, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      session: sessionId,
      email: await mail.address(),
      password: await mail.password()
    })
  });
}
```

2024-10-30 19:34 UTC, Chamber6821 commented
Да, заебок. Теперь обнови непосредственно код интерфейсов в соответсвии со сценариями и тем, что придумал

2024-10-30 19:35 UTC, Chamber6821 commented
И после изменений, раскидай все интерфейсы по файлам по шаблону: `Session` -> `src/session/Session.ts`. Это нужно для группировки реализаций интерфейсов по папкам

2024-10-31 19:25 UTC, Chamber6821 requested changes
Везде отступ 2 пробела и `export default interface` для интерфейсов

2024-10-31 19:25 UTC, Chamber6821 commented on src/session/Session.ts
> +}
Добавь сюда метод `delete` симметрично с `Mail`

2024-10-31 19:25 UTC, Chamber6821 commented on src/session/Sessions.ts
> +    create(mail: Mail): Promise<Session>
Этот метод замени лучше на `withAccount(account: Account): Promise<Session>`

2024-10-31 22:02 UTC, Chamber6821 requested changes

2024-11-01 10:31 UTC, Chamber6821 requested changes

2024-11-01 10:31 UTC, Chamber6821 commented on src/session/Sessions.ts
> +  withAccount(account: Account): Promise<Session>  // Replaced create method
Удали комент

2024-11-01 10:31 UTC, Chamber6821 commented on src/session/Session.ts
> +  asJson(): Promise<Json>
Передвинь этот метод в конец объявления интерфейса

2024-11-01 10:59 UTC, Chamber6821 requested changes
Последние исправление

2024-11-01 10:59 UTC, Chamber6821 commented on src/session/Sessions.ts
> +  withAccount(account: Account): Promise<Session>
Верни все таки просто `create` без аргументов, а то в этом случае нам нужно откуда-то брать аккаунт, а при обновлении сесии она внутри решает откуда взять аккаунт, какая-то двойственность получается

2024-11-01 11:10 UTC, Chamber6821 commented
@a9ek0 ты не туда вставил `create`. Он должен быть в интерфейсе `Sessions`

2024-11-01 15:25 UTC, Chamber6821 commented
Экспортируй каждый интерфейс по дефолту. Или есть какие-то причины так не делать?

2024-11-02 07:48 UTC, Chamber6821 approved these changes

2024-11-02 19:50 UTC, merged